- include: facts.yml

- name: Update Systems
  hosts: all
  become: true
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: centos, when: ansible_os_family == "RedHat" }
  handlers:
    - include: handlers/logging.yml
    - include: handlers/reboot.yml