- name: Ansible template example 
  hosts: all 
  tasks: 
   - name: Create the app.conf configuration file
     template:
       src: "/scripts/app.conf.j2"
       dest: "/etc/app.conf"
  become: true 