- name: Ansible template example 
  hosts: all
  remote_user: ubuntu   # Using Remote host as ubuntu 
  tasks: 
   - name: Create the app.conf configuration file
     template:
       src: "app.conf.j2"
       dest: "/etc/app.conf"
  become: true 