- name: Ansible template example 
  hosts: myserver 
  remote_user: ubuntu   # Using Remote host as ubuntu 
  tasks: 
   - name: Create the app.conf configuration file
     template:
       src: "~/ansible_template_demo/app.conf.j2"
       dest: "/etc/app.conf"
  become: true 