- name: Ansible template example 
  hosts: all
  remote_user: ubuntu   # Using Remote host as ubuntu 
  tasks: 
   - name: Create the app.conf configuration file
     template:
       url: "https://raw.githubusercontent.com/sandman-cs/ansible-test/main/app.conf.j2"
       dest: "/etc/app.conf"
  become: true 