---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: https://vcenter2.esilabs.com/
      username: csandberg@esilabs.com
#      password: vmware
      validate_certs: False
      name: aap-testvm_2
      template: aap-build-template
      datacenter: BPIC_vcenter2
      folder: /BPIC_vcenter2/aap-test
      state: poweredoff
      wait_for_ip_address: no