---
- hosts: all
  become: true
  tasks:
  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status
    when: ansible_os_family == "RedHat"

  - name: Remove packates not needed anymore
    yum:
      autoremove: yes
    when: ansible_os_family == "RedHat"

  - name: Reboot when packages were updated
    reboot:
    when: yum_update_status.changed

- hosts: all
  tasks:
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status
    when: ansible_os_family == "Debian"

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
    when: ansible_os_family == "Debian"

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed