- name: Survey Test
  hosts: all
  tasks:
    - name: Get Response from Survey
      syslogger:
        msg: "Hello from Ansible"
        priority: "err"
        facility: "user"
        log_pid: true