- name: Survey Test
  hosts: all
  tasks:
    - name: Get Response from Survey
      ansible.builtin.debug:
        msg: Answer {{ who_said_who }} 
    - name: Update all installed packages using YUM module
      debug: 
        msg: RHEL System
      when: ansible_os_family == "RedHat"
    - name: Update all installed packages using YUM module
      debug: 
        msg: Debian System
      when: ansible_os_family == "Debian"